source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TableViewAutolayoutManager_Example', :exclusive => true do
  pod "TableViewAutolayoutManager", :path => "../"
end

target 'TableViewAutolayoutManager_Tests', :exclusive => true do
  pod "TableViewAutolayoutManager", :path => "../"

  
end
